language: node_js
node_js:
- node
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
- rvm install `cat .ruby-version`
install:
- npm install
script:
- npm run-script build
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: production
